// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Versta.Data;

namespace Versta.Migrations
{
    [DbContext(typeof(VerstaDbContext))]
    [Migration("20210818184734_AddSampleData")]
    partial class AddSampleData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Versta.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfReceiving")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WeightInKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8802b717-6e18-4487-b904-1f6d2cc7c784"),
                            DateOfReceiving = new DateTime(2021, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecipientAddress = "Тверская улица 6, кв. 15",
                            RecipientCity = "Москва",
                            SenderAddress = "Невский проспект 5к2, кв. 212",
                            SenderCity = "Санкт-Петербург",
                            WeightInKg = 4.1230000000000002
                        },
                        new
                        {
                            Id = new Guid("983d5a87-e555-4175-b724-7403865b799b"),
                            DateOfReceiving = new DateTime(2022, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecipientAddress = "Невский проспект 5к2, кв. 212",
                            RecipientCity = "Санкт-Петербург",
                            SenderAddress = "Тверская улица 6, кв. 15",
                            SenderCity = "Москва",
                            WeightInKg = 15.122999999999999
                        },
                        new
                        {
                            Id = new Guid("8d8e8607-5268-4752-83bf-5d88a66986c2"),
                            DateOfReceiving = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecipientAddress = "ул. Серёгина 19, кв. 103",
                            RecipientCity = "Москва",
                            SenderAddress = "улица Габышева, кв. 56",
                            SenderCity = "Волгоград",
                            WeightInKg = 16.789000000000001
                        },
                        new
                        {
                            Id = new Guid("40c75d95-9a41-4c37-907d-9d6bd88e1196"),
                            DateOfReceiving = new DateTime(2021, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecipientAddress = "ул. Богданова 32, кв. 567",
                            RecipientCity = "Волгоград",
                            SenderAddress = "ул. Якубовичка 898, кв. 11",
                            SenderCity = "Санкт-Петербург",
                            WeightInKg = 24.98
                        },
                        new
                        {
                            Id = new Guid("c1e2b3e5-bc76-4c8f-bb61-a77569c64dff"),
                            DateOfReceiving = new DateTime(2022, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecipientAddress = "улица Труда 89, кв. 313",
                            RecipientCity = "Санкт-Петербург",
                            SenderAddress = "пер. Ващенко 19, кв. 789",
                            SenderCity = "Волгоград",
                            WeightInKg = 11.4
                        },
                        new
                        {
                            Id = new Guid("45c195f4-4c39-491c-8f68-48ef9fb86c6d"),
                            DateOfReceiving = new DateTime(2021, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RecipientAddress = "Читинская улица 1234, кв. 52",
                            RecipientCity = "Владивосток",
                            SenderAddress = "ул. Полухина, кв. 321",
                            SenderCity = "Волгоград",
                            WeightInKg = 18.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
